// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrlShortener.Infrastructure;

#nullable disable

namespace UrlShortener.Migrations
{
    [DbContext(typeof(UrlShortenerContext))]
    [Migration("20250130094446_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrlShortener.Entities.Counter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Concurrency")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("concurrency");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<long>("CurrentStartingValue")
                        .HasColumnType("bigint")
                        .HasColumnName("current_starting_value");

                    b.Property<long>("IncrementValue")
                        .HasColumnType("bigint")
                        .HasColumnName("increment_value");

                    b.Property<bool>("Invalidated")
                        .HasColumnType("boolean")
                        .HasColumnName("invalidated");

                    b.Property<long>("MaxValue")
                        .HasColumnType("bigint")
                        .HasColumnName("max_value");

                    b.HasKey("Id")
                        .HasName("pk_counter");

                    b.ToTable("counter", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Entities.Pair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<bool>("Invalidated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("invalidated");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("long_url");

                    b.Property<string>("ShortenUrl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("shorten_url");

                    b.HasKey("Id")
                        .HasName("pk_pair");

                    b.ToTable("pair", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Entities.Usage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AccessTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_time");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<bool>("Invalidated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("invalidated");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("PairId")
                        .HasColumnType("uuid")
                        .HasColumnName("pair_id");

                    b.Property<string>("Referer")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("referer");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_usage");

                    b.HasIndex("PairId")
                        .HasDatabaseName("ix_usage_pair_id");

                    b.ToTable("usage", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Entities.Usage", b =>
                {
                    b.HasOne("UrlShortener.Entities.Pair", "Pair")
                        .WithMany("Usages")
                        .HasForeignKey("PairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usage_pair_pair_id");

                    b.Navigation("Pair");
                });

            modelBuilder.Entity("UrlShortener.Entities.Pair", b =>
                {
                    b.Navigation("Usages");
                });
#pragma warning restore 612, 618
        }
    }
}
